/*
  The SERVER program: hello_server.c
  Modified to remove filler argument
*/

#include <stdio.h>
#include "hello.h"   /* generated by rpcgen and then modified */

int *
print_hello_1_svc(struct svc_req *req)
{
    static int ok;

    ok = printf("server : Hello, world.\n");

    return &ok;
}