/*
  The CLIENT program: hello_client.c
  Modified to remove filler argument
*/

#include <stdio.h>
#include <stdlib.h>
#include "hello.h"   /* generated by rpcgen and then modified */

int
main(int argc, char *argv[])
{
    CLIENT *client;
    int *return_value;
    char *server;

    if (argc != 2) {
        fprintf(stderr, "Usage: %s host_name\n", argv[0]);
        exit(1);
    }

    server = argv[1];

    /* Create RPC client handle */
    client = clnt_create(server, DISPLAY_PRG, DISPLAY_VER, "tcp");
    if (client == NULL) {
        clnt_pcreateerror(server);
        exit(2);
    }

    printf("client : Calling function.\n");

    /* Call remote function WITHOUT filler argument */
    return_value = print_hello_1(client);

    if (return_value && *return_value)
        printf("client : Mission accomplished.\n");
    else
        printf("client : Unable to display message.\n");

    return 0;
}